version: 2

models:
  - name: dim_customers
    description: "This is the dimension table for customers. It contains customer information such as customer ID, zip code, city, and state."
    columns:
      - name: customer_id
        description: "The unique identifier for each customer."
        tests:
          - unique
          - not_null
      - name: customer_zip_code_prefix
        description: "The zip code prefix of the customer's address."
      - name: customer_city
        description: "The city where the customer resides."
      - name: total_orders
        description: "The total number of orders placed by the customer."
      - name: total_delivered_orders
        description: "The total number of orders delivered to the customer."
      - name: total_canceled_orders
        description: "The total number of orders canceled by the customer."
      - name: total_shipped_orders
        description: "The total number of orders shipped to the customer."
      - name: lifetime_payment_value
        description: "The total value of all payments made by the customer."
      - name: avg_payment_value
        description: "The average value of payments made by the customer."
      - name: min_payment_value
        description: "The minimum value of any single payment made by the customer."
      - name: max_payment_value
        description: "The maximum value of any single payment made by the customer."
      - name: first_order_date
        description: "The date of the customer's first order."
      - name: last_order_date
        description: "The date of the customer's last order."
  - name: fct_orders
    description: "This is the fact table for orders. It contains information about each order, such as order ID, customer ID, order status, and payment details."
    columns:
      - name: order_id
        description: "The unique identifier for each order."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "The unique identifier for the customer who placed the order."
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_id
      - name: order_status
        description: "The current status of the order (e.g., delivered, canceled)."
        tests:
          - not_null
          - accepted_values:
              arguments:
                values:
                  [
                    delivered,
                    shipped,
                    canceled,
                    approved,
                    unavailable,
                    processing,
                    invoiced,
                    created,
                  ]
      - name: order_purchase_date
        description: "The date when the order was placed."
        tests:
          - not_null
      - name: order_approved_date
        description: "The date when the order was approved."
      - name: order_delivered_carrier_date
        description: "The date when the order was delivered to the carrier."
      - name: order_delivered_customer_date
        description: "The date when the order was delivered to the customer."
      - name: order_estimated_delivery_date
        description: "The estimated delivery date for the order."
